### ISSUE TITLE
add artifact download link from codevision

### ISSUE THREAD

**Issue by teaalltr** [kant2002/ghidra-official#5]
And if you want, you could also keep a mirror of the NSA master branch so it can be built automatically 😄

**Comment by kant2002** [comment]
I add the publishing of the artifacts on build, if that's what do you want.
master is already keep track of upstream, but these mirroring not automated. If you know how I can keep these changes automatically would be good to know.

**Comment by teaalltr** [comment]
Thanks! Are you planning adding Windows/Mac CI build too?

**Comment by kant2002** [comment]
Yes, I think It's doable with Azure Dev Ops. If you want, you can make PR which do that. 
I just have to play with build matrix which is unknown to me yet. 
I actually want to pickup low-hanging fruit and take all small things which Ghidra, so if you have anything interesting, you can submit PR. I do not want to do refactoring there, but some important quality of life things are should be there, in my opinion for community's sake.

If you have idea how current Ghidra can produce Jars for Maven, I can add that too, since I suppose Ghidra would not maintain that as part of their build.

**Comment by kant2002** [comment]
Mac is there. Only Windows left. Have to play with downloading bison and flex
